steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/interview-project-442915/python-hello-world:$SHORT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/interview-project-442915/python-hello-world:$SHORT_SHA'
  - name: ubuntu
    entrypoint: bash
    args:
      - '-c'
      - >
        sed -i "s|image:
        gcr.io/interview-project-442915/python-hello-world:.*|image:
        gcr.io/interview-project-442915/python-hello-world:$SHORT_SHA|"
        k8/deployment.yaml
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    secretEnv:
      - GITHUB_SSH_KEY
    args:
      - '-c'
      - >
        mkdir -p ~/.ssh

        echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa

        chmod 600 ~/.ssh/id_rsa

        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

        git config --global user.email "arsh.kharbanda2010@gmail.com"

        git config --global user.name "arshkharbanda2010"

        git remote set-url origin
        git@github.com:arshkharbanda2010/interview-task.git

        git add k8/deployment.yaml

        git commit -m "Update image tag to $SHORT_SHA"

        git push origin master
substitutions:
  _SHORT_SHA: $SHORT_SHA
timeout: 1200s
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
secrets:
  - secretEnv:
      GITHUB_SSH_KEY: projects/interview-project-442915/secrets/GITHUB_SSH_KEY/versions/latest