steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/interview-project-442915/python-hello-world:latest', '.']

# Step 2: Push the Docker image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/interview-project-442915/python-hello-world:latest']

# Step 3: Update the Kubernetes manifest with the new image tag
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed -i "s|image: gcr.io/interview-project-442915/python-hello-world:.*|image: gcr.io/interview-project-442915/python-hello-world:latest|" k8/deployment.yaml

# Step 4: Commit the updated manifest back to GitHub
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config --global user.email "arsh.kharbanda2010@gmail.com"
    git config --global user.name "arshkharbanda2010"
    git add k8/deployment.yaml
    git commit -m "Update image tag to latest"
    git push origin main

# substitutions:
#   _SHORT_SHA: 'latest'  # Default value for testing; replace with dynamic SHA as needed

timeout: 1200s

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
