apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-hello-world
  template:
    metadata:
      labels:
        app: python-hello-world
    spec:
      containers:
      - name: python-hello-world
        image: gcr.io/interview-project-442915/python-hello-world:latest
        ports:
        - containerPort: 8080
##