apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world
  labels:
    app: python-hello-world
  annotations:  # Add ArgoCD Image Updater annotations here
    argocd-image-updater.argoproj.io/image-list: gcr.io/interview-project-442915/python-hello-world
    argocd-image-updater.argoproj.io/python-hello-world.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-hello-world
  template:
    metadata:
      labels:
        app: python-hello-world
    spec:
      containers:
      - name: python-hello-world
        image: gcr.io/interview-project-442915/python-hello-world:47ef4f6
        ports:
        - containerPort: 8080
