apiVersion: v1
kind: Service
metadata:
  name: python-hello-world
  labels:
    app: python-hello-world
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: python-hello-world
  type: LoadBalancer
